# Site settings
title: Not a Number
email: nan@nan.nyc 
description: > # this means to ignore newlines until "baseurl:"
  here, we are not only numbers
baseurl: "" 
url: "https://nan.nyc" 

# Collections
collections:
  wiki:
    output: true
  chapters:
    output: true
 
defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki-entry"
      permalink: /tce/wiki/:path/
  - scope:
      path: "tce/blog"
      type: "posts"
    values:
      layout: "tce-post"
      permalink: /tce/blog/:title/
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "tce-chapter"
      permalink: /tce/:path/
      footer: "cc-by-nc-nd"

# Build settings
markdown: kramdown
permalink: /:categories/:title
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

#other options
timezone: America/New_York
exclude:	[old, _scripts, _drafts]
